name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push application.server
        uses: docker/build-push-action@v2
        with:
          context: application/server
          push: true
          tags: itshujia/fabric-realty.server:latest
      - name: Build and push application.web
        uses: docker/build-push-action@v2
        with:
          context: application/web
          push: true
          tags: itshujia/fabric-realty.web:latest
